IF
  GlobalLT("CbPartyHasKilledAllBandits","GLOBAL",3)
  Global("Towershut","ar4307",0)
THEN
  RESPONSE #100
  SetGlobal("Towershut","ar4307",1)
    CloseDoor("Door06")
    Lock("Door06")
    CloseDoor("Door07")
    Lock("Door07")
END

IF
  GlobalGT("CbPartyHasKilledAllBandits","GLOBAL",2)
  Global("Toweropen","ar4307",0)
THEN
  RESPONSE #100
  SetGlobal("Toweropen","ar4307",1)
    Unlock("Door07")
    OpenDoor("Door07")
END

