IF
  OR(2)
    Entered([ANYONE])
    Opened([ANYONE])
THEN
  RESPONSE #100
    DisplayString(LastTrigger,14381)  // ~Trap Sprung~ [AMB_D05C]
    ForceSpell(LastTrigger,TRAP_ARROW_BITING)
    ForceSpell(LastTrigger,TRAP_ARROW_BITING)
    ForceSpell(LastTrigger,TRAP_ARROW_BITING)
    ForceSpell(LastTrigger,TRAP_ARROW_BITING)
    TriggerActivation(Myself,FALSE)
    CreateCreature("CBMMOUTH",[893.861],0)  // ~Magic Mouth~
END

